resources:
 - name: resource_pipelines123
   type: GitRepo
   configuration:
     gitProvider: github_kirti
     path: kirtisahu05/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^master$
pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines123
        execution:
          onExecute:
            - printenv



      
